# Generated by Django 2.1.3 on 2018-11-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='posts.Category'),
            preserve_default=False,
        ),
    ]
