# Generated by Django 2.1.3 on 2018-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('PPU', 'Pending published')], default='PUB', max_length=3),
        ),
    ]
