# Generated by Django 2.1.3 on 2018-11-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_video',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
