# Generated by Django 2.1.3 on 2018-11-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20181123_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys_post',
            name='categorys',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorys_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
        migrations.DeleteModel(
            name='Categorys_Post',
        ),
    ]
