# Generated by Django 2.1.3 on 2018-11-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20181123_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S'),
        ),
    ]
