# Generated by Django 2.1.3 on 2018-11-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20181123_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categorys',
        ),
    ]
