# Generated by Django 2.1.3 on 2018-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20181123_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_video',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
