# Generated by Django 2.1.3 on 2018-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20181124_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_featured', models.FileField(upload_to='')),
            ],
        ),
    ]
