# Generated by Django 2.1.3 on 2018-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_postimagefeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(max_length=200, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_image',
            field=models.CharField(max_length=100, verbose_name='Url de la imagen'),
        ),
    ]
