# Generated by Django 2.1.3 on 2018-11-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='owner',
            new_name='user',
        ),
    ]
